### ISSUE TITLE
Расширение Хром ошибка 404

### ISSUE THREAD

**Issue by Sogl** [typograf/red-typography-webextension#15]
Можно ли перевыложить? 
или получить в запакованном виде для ручной инсталляции?

**Comment by Sogl** [comment]
Клонировал репо, собрал расширения. Хром ругается на старый манифест версии 2, но пока работает.

При этом выделяю текст в поле textarea, жму "Типографировать" и реакции 0. 
@hcodes В чем может быть проблема?

**Comment by hcodes** [comment]
Перевыложил.
