### ISSUE TITLE
Не работает в Chrome и Firefox

### ISSUE THREAD

**Issue by daniilnikitin** [typograf/red-typography-webextension#2]
Благодарю за потенциальную экономию колоссального времени! Я контентщик и сейчас мне нужно оттипографить кучу страниц. Если бы у меня была возможность делать это из контекстного меню - я бы сэкономил кучу времени!

Установил расширения для Chrome и Firefox, перезагрузил браузеры (и даже компьютер). Выделяю текст в поле для ввода кода страницы, нажимаю в контекстном меню оттипографить - ничего не меняется.
Типографлю с теми же настройками тут: https://typograf.github.io/ - типографится.

Что я делаю не так?
![image](https://user-images.githubusercontent.com/20316574/69490368-e69b2800-0e97-11ea-84a4-79a8f5b75442.png)
![image](https://user-images.githubusercontent.com/20316574/69490388-206c2e80-0e98-11ea-9fea-ba0baee847ee.png)
![image](https://user-images.githubusercontent.com/20316574/69490397-409bed80-0e98-11ea-8518-b90379e262af.png)

**Comment by hcodes** [comment]
На некоторых сайтах дополнение не работает. Например, если на сайте используется React. На каком сайте проблема?

**Comment by daniilnikitin** [comment]
Денис, приветствую! Приношу извинения за долгий ответ. Да, я работаю с сайтом через корпоративный VPN и возможно ваш сервис не мог через него обратиться к внешним серверам. Но сейчас всё само заработало!)) Может быть ребята на работе что-то подшаманили. Благодарю! Ваш продукт экономит кучу времени!
